# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'FlipFlop_Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlipFlop_Sample
pod "FlipFlopLiteSDK", '1.2.1'
pod 'SDWebImage', '~> 5.0'
pod 'Alamofire'
pod 'NVActivityIndicatorView'
pod 'YUCIHighPassSkinSmoothing', '1.4'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
